#!/bin/bash
set -e

source ./common.sh

FILE=/etc/cron.d/restic

echo "Installing crontab to $FILE"
printf "# This file is autogenerated by /etc/restic install_cron.sh script.\n# DO NOT CHANGE contents of this file as it will get overwritten!\n" > $FILE

if [ -n "$BACKUP_CRON" ]
then
  echo "$BACKUP_CRON root /bin/bash /etc/restic/backup.sh > /dev/null" >> $FILE
fi

if [ -n "$PRUNE_CRON" ]
then
  echo "$PRUNE_CRON root /bin/bash /etc/restic/prune.sh > /dev/null" >> $FILE
fi

if [ -n "$AUTO_UPDATE" ]
then
  echo "0 */12 * * * root /bin/bash /etc/restic/update.sh > /dev/null" >> $FILE
fi